name: Publish Docker
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
      - uses: elgohr/Publish-Docker-Github-Action@master
      - with:
          registry: ghcr.io
          name: ghcr.io/afanasievkirill/nestjs_example/nestjs_api_example
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: top-api/Dockerfile
          workdir: top-api/
          tags: "develop" 